from selenium.webdriver.common.by import By

class Locators:
    MY_ACCOUNT_BUTTON = (By.LINK_TEXT, "Личный Кабинет")
    NAME =(By.XPATH,"//input[@type='text' and @name='name' and contains(@class, 'input__textfield')]")
    EMAIL = (By.XPATH, "//div[@class='input pr-6 pl-6 input_type_text input_size_default']//input[contains(@class, 'input__textfield')]")
    PASSWORD = (By.NAME, "Пароль")
    REG_BUTTON = (By.XPATH, "//button[contains(@class, 'button_button_type_primary__1O7Bx') and text()='Зарегистрироваться']")
    ERROR_MESSAGE = (By.XPATH, "//p[contains(@class, 'input__error')]")
    LOGIN_FORM = (By.XPATH, "//h2[text()='Вход']")
    LOGIN_TO_YOUR_ACCOUNT_BUTTON = (By.XPATH, "//button[contains(@class, 'button_button_type_primary__1O7Bx') and text()='Войти в аккаунт']")
    LOGIN_BUTTON = (By.XPATH, "//button[contains(@class, 'button_button_type_primary__1O7Bx') and text()='Войти']")
    PLACE_ORDER_BUTTON = (By.XPATH, "//button[contains(@class, 'button_button_type_primary__1O7Bx') and text()='Оформить заказ']")
    ENTER_BUTTON = (By.XPATH, "//button[contains(@class, 'button_button_type_primary__1O7Bx') and text()='Войти']")
    LOGIN_BUTTON_VIA_REG_FORM = (By.XPATH, "//a[contains(@class, 'Auth_link__1fOlj') and text()='Войти']")
    LOGIN_BUTTON_IN_PASSWORD_RESET_PAGE = (By.XPATH, "//a[contains(@class, 'Auth_link__1fOlj') and text()='Войти']")
    PROFILE = (By.LINK_TEXT, 'Профиль')
    CONSTRUCTOR_BUTTON = (By.XPATH, "//p[contains(@class, 'AppHeader_header__linkText__3q_va') and text()='Конструктор']")
    EXIT_BUTTON = (By.XPATH, "//button[contains(@class, 'text_type_main-medium') and text()='Выход']")
    BUNS_BUTTON = (By.XPATH, "//div[contains(@class, 'tab_tab__1SPyG')]//span[text()='Булки']")
    BUNS_SECTION_TEXT = (By.XPATH, "//h2[contains(@class, 'text_type_main-medium') and text()='Булки']")
    SOUS_SECTION_TEXT = (By.XPATH, "//h2[contains(@class, 'text_type_main-medium') and text()='Соусы']")
    SOUS_BUTTON = (By.XPATH, '//div[contains(@class, "tab_tab__1SPyG")]//span[text()="Соусы"]')
    FILLING_BUTTON = (By.XPATH, '//div[contains(@class, "tab_tab__1SPyG")]//span[text()="Начинки"]')
    FILLING_SECTION_TEXT = (By.XPATH, "//h2[contains(@class, 'text_type_main-medium') and text()='Начинки']")
    ACTIVE_TAB_SOUS = (By.XPATH, "//div[contains(@class, 'tab_tab__1SPyG')]//span[text()='Соусы']")
    ACTIVE_TAB_BUNS = (By.XPATH, "//div[contains(@class, 'tab_tab__1SPyG')]//span[text()='Булки']")
    ACTIVE_TAB_FILLING = (By.XPATH, "//div[contains(@class, 'tab_tab__1SPyG')]//span[text()='Начинки']")
